// playground/src/Playground.tsx
import React, { useRef, useState } from 'react'
import {
    Alert,
    Blockquote,
    Button,
    Container,
    Drawer,
    Tabs,
    Textarea,
    Title,
    NavLink
} from '@mantine/core'
import chroma from 'chroma-js'
import { Example, examples } from './examples'

import { expressionToGraphQL, search } from 'graphql-jmespath'
import { request } from 'graphql-request'
import { Prism } from '@mantine/prism'
import { Cell, Pie, PieChart } from 'recharts'
import { IconAlertCircle } from '@tabler/icons'

export const Playground: React.FC = () => {
    const [backendUrl, setBackendUrl] = useState(
        'https://countries.trevorblades.com/'
    )
    const [expression, setExpression] = useState('')
    const [graphqlQuery, setGraphqlQuery] = useState('')
    const [graphqlData, setGraphqlData] = useState()
    const [error, setError] = useState('')
    const [jmesPathResult, setJmespathResult] = useState<any>()

    const [example, setExample] = useState<Example>()

    const loadExample = async (selectedExample: Example) => {
        setExample(selectedExample)
        setExpression(selectedExample.expression)
        refInput.current?.setSelectionRange(
            selectedExample.expression.length,
            selectedExample.expression.length
        )
        refInput.current?.focus()
        await run(selectedExample.expression)
        setActiveTab(
            selectedExample.chart ? 'jmespath-chart' : 'jmespath-result'
        )
        refInput.current?.focus()
    }

    const [activeTab, setActiveTab] = useState<string | null>('graphql-query')

    const run = async (exp?: string) => {
        setError('')
        if (!exp) {
            setError('No expression')
            return
        }
        try {
            const query = expressionToGraphQL(exp, { pretty: true })
            if (query !== graphqlQuery) {
                setGraphqlQuery(query)
                try {
                    const gqlData = await request(backendUrl, query)
                    setGraphqlData(gqlData)
                    const jmesData = search(gqlData, exp)
                    setJmespathResult(jmesData)
                } catch (e: any) {
                    setError(e.response?.errors?.[0]?.message || e.message)
                    setGraphqlData(undefined)
                    setJmespathResult(undefined)
                }
            } else {
                const jmesData = search(graphqlData, exp)
                setJmespathResult(jmesData)
            }
        } catch (e) {
            const err = e as Error
            setError(err.message)
        }
    }

    const refInput = useRef<HTMLTextAreaElement>(null)

    const [examplesDrawerOpened, setExamplesDrawerOpened] = useState(false)
    return (
        <Container>
            <Title>Playground</Title>

            <Drawer
                opened={examplesDrawerOpened}
                onClose={() => setExamplesDrawerOpened(false)}
                title="Examples"
                padding="md"
                size="xl"
            >
                {examples.map((example) => (
                    <NavLink
                        key={example.expression}
                        onClick={() => {
                            setExamplesDrawerOpened(false)
                            loadExample(example)
                        }}
                        label={example.expression}
                        description={example.description}
                    />
                ))}
            </Drawer>
            <Button onClick={() => setExamplesDrawerOpened(true)}>
                Load an example
            </Button>

            {example && <Blockquote>{example.description}</Blockquote>}

            <Textarea
                ref={refInput}
                placeholder="Expression"
                label="Expression"
                value={expression}
                rows={1}
                autosize
                autoFocus
                onChange={(event) =>
                    setExpression(event.currentTarget.value.replace(/\n/g, ''))
                }
                onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                        e.preventDefault()
                        run(expression)
                    }
                }}
                style={{ wordWrap: 'break-word', wordBreak: 'break-all' }}
            />

            {error && (
                <Alert
                    icon={<IconAlertCircle size={16} />}
                    title="Error"
                    color="red"
                >
                    {error}
                </Alert>
            )}

            <Tabs value={activeTab} onTabChange={setActiveTab}>
                <Tabs.List>
                    <Tabs.Tab value="graphql-query">GraphQL Query</Tabs.Tab>
                    <Tabs.Tab value="graphql-data">GraphQL Data</Tabs.Tab>
                    <Tabs.Tab value="jmespath-result">JMESPath Result</Tabs.Tab>
                    {example?.chart && (
                        <Tabs.Tab value="jmespath-chart">
                            JMESPath Chart
                        </Tabs.Tab>
                    )}
                </Tabs.List>

                <Tabs.Panel value="graphql-query" pt="xs">
                    <Prism language="graphql">{graphqlQuery}</Prism>
                </Tabs.Panel>

                <Tabs.Panel value="graphql-data" pt="xs">
                    {graphqlData && (
                        <Prism language="json">
                            {JSON.stringify(graphqlData, null, 2)}
                        </Prism>
                    )}
                </Tabs.Panel>

                <Tabs.Panel value="jmespath-result" pt="xs">
                    {jmesPathResult && (
                        <Prism language="json">
                            {JSON.stringify(jmesPathResult, null, 2)}
                        </Prism>
                    )}
                </Tabs.Panel>

                <Tabs.Panel value="jmespath-chart" pt="xs">
                    {example?.chart &&
                        jmesPathResult &&
                        example.chart.type === 'pie' && (
                            <PieChart width={730} height={250}>
                                <Pie
                                    animationDuration={500}
                                    data={jmesPathResult}
                                    nameKey={example.chart.key}
                                    dataKey={example.chart.value}
                                    label={(entry) => entry.name}
                                >
                                    {jmesPathResult.map(
                                        (_: any, index: number) => (
                                            <Cell
                                                key={index}
                                                fill={
                                                    chroma
                                                        .scale([
                                                            '#fafa6e',
                                                            '#ff6d93'
                                                        ])
                                                        .mode('lch')
                                                        .colors(
                                                            jmesPathResult.length
                                                        )[index]
                                                }
                                            />
                                        )
                                    )}
                                </Pie>
                            </PieChart>
                        )}
                </Tabs.Panel>
            </Tabs>
        </Container>
    )
}

// examples/src/components/Playground.vue
<template>
    <q-card>
        <q-card-section>
            <q-btn color="primary" label="Load an example">
                <q-menu>
                    <q-list style="min-width: 100px">
                        <q-item clickable v-close-popup v-for="example in examples"
                            @click="() => loadExample(example)">
                            <q-item-section>{{ example.expression }}</q-item-section>
                        </q-item>
                    </q-list>
                </q-menu>
            </q-btn>
        </q-card-section>
        <q-card-section v-if="example">
            {{ example.description }}
        </q-card-section>
        <q-card-section>
            <q-form @submit="run">
                <q-input v-model="expression" label="Expression">
                    <template v-slot:append>
                        <q-btn round dense flat icon="send" @click="run" :disable="!expression" />
                    </template>
                </q-input>
            </q-form>
            <!-- TODO improve the error section -->
            <div v-if="error">
                {{ error }}
            </div>
        </q-card-section>
        <q-card-section>
            <q-tabs v-model="activeTab" dense active-color="primary" indicator-color="primary" align="justify"
                inline-label>
                <q-tab name="graphql-query" icon="mdi-graphql" col label="GraphQL Query" />
                <q-tab name="graphql-data" icon="mdi-graphql" label="GraphQL Result" />
                <q-tab name="jmespath-result" icon="mdi-code-json" label="JMESPath Result" />
                <q-tab name="jmespath-chart" icon="mdi-chart-line" label="JMESPath Chart" v-if="example?.chart" />
            </q-tabs>
            <q-separator />

            <q-tab-panels v-model="activeTab" animated>
                <q-tab-panel name="graphql-query">
                    <Code language="graphql" :value="graphqlQuery" />
                </q-tab-panel>

                <q-tab-panel name="graphql-data">
                    <Code v-if="graphqlData" language="json" :value="JSON.stringify(graphqlData, null, 2)"
                        :truncate="5000" />
                    <div v-else>Empty GraphQL result</div>
                </q-tab-panel>

                <q-tab-panel name="jmespath-result">
                    <Code v-if="jmespathResult" language="json"
                        :value="JSON.stringify(jmespathResult, null, 2)"
                        :truncate="5000" />
                    <div v-else>Empty JMESPath result</div>
                </q-tab-panel>
                <q-tab-panel name="jmespath-chart" v-if="example?.chart">
                    <Chart :options="example.chart" :data="jmespathResult" />
                </q-tab-panel>
            </q-tab-panels>
        </q-card-section>
    </q-card>

</template>

<script lang="ts" setup>
import { ref } from 'vue'
import { useQuasar } from 'quasar'

import { request } from 'graphql-request'
import { expressionToGraphQL, search } from 'graphql-jmespath'
import Chart from './Chart.vue'

import { Example, examples } from '../examples'
import Code from './Code.vue'

const $q = useQuasar()

const backendUrl = ref('https://countries.trevorblades.com/')


const expression = ref('')
const graphqlQuery = ref('')
const graphqlData = ref()
const error = ref('')
const jmespathResult = ref()


const example = ref<Example>()

const loadExample = async (selectedExample: Example) => {
    example.value = selectedExample
    // graphqlQuery.value = ''
    expression.value = selectedExample.expression
    run()
    goToResultTab()
}

// * UI refs
const activeTab = ref<
    'graphql-query' | 'graphql-data' | 'jmespath-result' | 'jmespath-chart'
>('graphql-query')

const goToResultTab = () => {
    activeTab.value = example.value?.chart ? 'jmespath-chart' : 'jmespath-result'
}

/**
 * Transform the JMESPath expression to a GraphQL query
 */
const transformToGraphQL = () => {
    error.value = ''
    if (!expression.value) {
        error.value = 'No expression'
        throw Error()
    }
    try {
        const newQuery = expressionToGraphQL(expression.value, {
            pretty: true
        })
        if (newQuery !== graphqlQuery.value) {
            graphqlQuery.value = newQuery
            graphqlData.value = ''
            jmespathResult.value = null
            return true
        }

    } catch (e: any) {
        error.value = e.message
        graphqlQuery.value = ''
        throw Error()
    }
    return false
}

/**
 * Fetch the data from the GraphQL endpoint with the generated GraphQL query
 */
const fetchData = async () => {
    error.value = ''
    if (graphqlQuery.value) {
        $q.loading.show()
        try {
            graphqlData.value = await request(backendUrl.value, graphqlQuery.value)
        } catch (e: any) {
            error.value = e.response?.errors?.[0]?.message || e.message
            graphqlData.value = ''
            throw Error()
        } finally {
            $q.loading.hide()
        }
    }
}

/** 
 * Transform the GraphQL data with the JMESPath expression 
 */
const transformData = () => {
    error.value = ''
    try {
        jmespathResult.value = search(graphqlData.value, expression.value)
    } catch (e: any) {
        error.value = e.message
        jmespathResult.value = jmespathResult
        throw Error()
    }
}

const run = async (e?: Event) => {
    error.value = ''
    try {
        const isNewGraphQLQUery = transformToGraphQL()
        if (isNewGraphQLQUery) {
            // * Fetch new data only if the GraphQL query has changed
            await fetchData()
        }
        transformData()
        if (activeTab.value === 'graphql-query') {
            goToResultTab()
        }

    } catch {
        activeTab.value = 'graphql-query'
    }

}


</script>
